# Generated by `gtnh-nix gen` from the pack's
# startserver-java9.sh + java9args.txt. Re-run gen to refresh.
{
  xms = "6G";
  xmx = "6G";
  opts = [
    "-Dfml.readTimeout=180"
    "--illegal-access=warn"
    "-Djava.security.manager=allow"
    "-Dfile.encoding=UTF-8"
    "--add-opens java.base/jdk.internal.loader=ALL-UNNAMED"
    "--add-opens java.base/java.net=ALL-UNNAMED"
    "--add-opens java.base/java.nio=ALL-UNNAMED"
    "--add-opens java.base/java.io=ALL-UNNAMED"
    "--add-opens java.base/java.lang=ALL-UNNAMED"
    "--add-opens java.base/java.lang.reflect=ALL-UNNAMED"
    "--add-opens java.base/java.text=ALL-UNNAMED"
    "--add-opens java.base/java.util=ALL-UNNAMED"
    "--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED"
    "--add-opens java.base/sun.nio.ch=ALL-UNNAMED"
    "--add-opens java.desktop/sun.awt.image=ALL-UNNAMED"
    "--add-modules jdk.dynalink"
    "--add-opens jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED"
    "--add-modules java.sql.rowset"
    "--add-opens java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED"
  ];
}
