{lib, ...}: {
  bettercrashes = lib.mkOption {
    description = "bettercrashes configuration (./config/bettercrashes.cfg)";
    default = {};
    type = lib.types.submodule {
      options = {
        path = lib.mkOption {
        type = lib.types.str;
        default = "./config/bettercrashes.cfg";
        readOnly = true;
        };
        kind = lib.mkOption {
        type = lib.types.str;
        default = "forge";
        readOnly = true;
        };
        general = lib.mkOption {
          default = {};
          type = lib.types.submodule {
            options = {
              crashLogLimitClient = lib.mkOption {
                type = lib.types.int;
                default = 30;
                description = "Maximum number of crash logs generated per restart for client. Suppresses too many logs generated by continuous crashes. [range: 0 ~ 2147483647, default: 30]";
              };
              crashLogLimitServer = lib.mkOption {
                type = lib.types.int;
                default = 30;
                description = "Maximum number of crash logs generated per restart for server. Suppresses too many logs generated by continuous crashes. [range: 0 ~ 2147483647, default: 30]";
              };
              crashLogPasteService = lib.mkOption {
                type = lib.types.str;
                default = "mclo.gs";
                description = "Service to use for uploading crashlogs. Currently, only mclo.gs is currently supported. [default: mclo.gs]";
              };
              issueTrackerURL = lib.mkOption {
                type = lib.types.str;
                default = "https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues?q=label%3ACrash";
                description = "Link to a bug tracker. [default: ]";
              };
              stacktraceDeobfuscation = lib.mkOption {
                type = lib.types.bool;
                default = true;
                description = "Enables clearer stacktraces by deobfuscating vanilla methods using MCP. [default: true]";
              };
              unsupportedMods = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                description = "List of modids of mods that are not supported by the modpack. BetterCrashes will encourage the player to mention those specifically in their bug report. Optifine will always be detected. [default: ]";
              };
            };
          };
        };
      };
    };
  };
}
