//! Extract the pack's JVM launcher configuration into per-version
//! `launcher.nix` data: `-Xms`/`-Xmx` heap sizes and the rest of the
//! command-line opts (system properties + `--add-opens` / `--add-modules`
//! set).
//!
//! Reads two files at the pack root:
//!
//! - `startserver-java9.sh` — locates the `java …` invocation and
//!   tokenises its arguments. `@file` references (e.g. `@java9args.txt`)
//!   are expanded inline.
//! - `java9args.txt` (and any other `@`-referenced file) — line-based
//!   set of additional JVM flags.
//!
//! Filters out `-jar <jar>` and the trailing `nogui`, since the
//! `-jar` selection and gui mode are decided by `service.nix`.
//! Two-token flags (`--add-opens java.base/foo=…`) are joined into
//! a single string so they survive Nix's later `concatStringsSep " "`
//! into a shell command line.

use std::fs;
use std::io;
use std::path::Path;

pub struct LauncherData {
    pub xms: String,
    pub xmx: String,
    pub opts: Vec<String>,
}

pub fn extract_from_pack(pack_root: &Path) -> io::Result<LauncherData> {
    let sh = pack_root.join("startserver-java9.sh");
    let sh_text = fs::read_to_string(&sh)?;
    let java_line = sh_text
        .lines()
        .find(|l| l.trim_start().starts_with("java "))
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("no `java` invocation in {}", sh.display()),
            )
        })?;

    let mut tokens: Vec<String> = java_line
        .split_whitespace()
        .skip(1)
        .map(String::from)
        .collect();

    // Inline-expand `@file` references against the pack root.
    let mut i = 0;
    while i < tokens.len() {
        if let Some(filename) = tokens[i].strip_prefix('@') {
            let path = pack_root.join(filename);
            let text = fs::read_to_string(&path)?;
            let file_tokens: Vec<String> = text.split_whitespace().map(String::from).collect();
            tokens.splice(i..=i, file_tokens);
        } else {
            i += 1;
        }
    }

    let mut data = LauncherData {
        xms: String::new(),
        xmx: String::new(),
        opts: Vec::new(),
    };

    let mut i = 0;
    while i < tokens.len() {
        let t = &tokens[i];
        if let Some(v) = t.strip_prefix("-Xms") {
            data.xms = v.to_string();
            i += 1;
        } else if let Some(v) = t.strip_prefix("-Xmx") {
            data.xmx = v.to_string();
            i += 1;
        } else if t == "-jar" {
            // Skip this token and the jar filename that follows.
            i += 2;
        } else if t == "nogui" {
            i += 1;
        } else if (t == "--add-opens" || t == "--add-modules") && i + 1 < tokens.len() {
            data.opts.push(format!("{} {}", t, tokens[i + 1]));
            i += 2;
        } else {
            data.opts.push(t.clone());
            i += 1;
        }
    }

    Ok(data)
}

pub fn write_nix(data: &LauncherData, dest: &Path) -> io::Result<()> {
    let mut s = String::new();
    s.push_str("# Generated by `gtnh-nix gen` from the pack's\n");
    s.push_str("# startserver-java9.sh + java9args.txt. Re-run gen to refresh.\n");
    s.push_str("{\n");
    s.push_str(&format!("  xms = \"{}\";\n", escape(&data.xms)));
    s.push_str(&format!("  xmx = \"{}\";\n", escape(&data.xmx)));
    s.push_str("  opts = [\n");
    for opt in &data.opts {
        s.push_str(&format!("    \"{}\"\n", escape(opt)));
    }
    s.push_str("  ];\n");
    s.push_str("}\n");
    fs::write(dest, s)
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn td(name: &str) -> std::path::PathBuf {
        let tmp = std::env::temp_dir().join(format!("gtnh-launcher-test-{}-{}", name, std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();
        tmp
    }

    #[test]
    fn extracts_xms_xmx_and_combines_add_opens() {
        let pack = td("basic");
        fs::write(
            pack.join("startserver-java9.sh"),
            "#!/bin/bash\n   java -Xms6G -Xmx8G -Dfml.readTimeout=180 @java9args.txt nogui\n",
        )
        .unwrap();
        fs::write(
            pack.join("java9args.txt"),
            "--add-opens\njava.base/java.io=ALL-UNNAMED\n--add-modules jdk.dynalink\n-jar\nlwjgl3ify-forgePatches.jar\n",
        )
        .unwrap();

        let data = extract_from_pack(&pack).unwrap();
        assert_eq!(data.xms, "6G");
        assert_eq!(data.xmx, "8G");
        assert_eq!(
            data.opts,
            vec![
                "-Dfml.readTimeout=180",
                "--add-opens java.base/java.io=ALL-UNNAMED",
                "--add-modules jdk.dynalink",
            ]
        );
    }
}
